Repository sk-prj-genai-question-app/frontend, pull requests merged in 2025-07, with the labels that each got.

#5 [FEAT] 내 정보 및 오답노트 페이지, 상단 바
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/correct.png
  public/edit-icon.png
  public/edit-user.png
  public/logout.png
  public/user.png
  public/vite.svg
  public/wrong.png
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/AppLayout.css
  src/components/AppLayout.jsx
  src/components/ExamInfoCard.css
  src/components/ExamInfoCard.jsx
  src/components/ProfileCard.css
  src/components/ProfileCard.jsx
  src/components/ProgressCard.css
  src/components/ProgressCard.jsx
  src/components/Sidebar.css
  src/components/Sidebar.jsx
  src/components/TopBar.css
  src/components/TopBar.jsx
  src/index.css
  src/main.jsx
  src/pages/MyPage.css
  src/pages/MyPage.jsx
  src/pages/WrongNotePage.css
  src/pages/WrongNotePage.jsx
  vite.config.js
Labels: feature

#8 [FEAT] 내 정보 및 오답노트 페이지, 상단 바
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/correct.png
  public/edit-icon.png
  public/edit-user.png
  public/logout.png
  public/user.png
  public/vite.svg
  public/wrong.png
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/AppLayout.css
  src/components/AppLayout.jsx
  src/components/ExamInfoCard.css
  src/components/ExamInfoCard.jsx
  src/components/ProfileCard.css
  src/components/ProfileCard.jsx
  src/components/ProgressCard.css
  src/components/ProgressCard.jsx
  src/components/TopBar.css
  src/components/TopBar.jsx
  src/index.css
  src/main.jsx
  src/pages/MyPage.css
  src/pages/MyPage.jsx
  src/pages/WrongNotePage.css
  src/pages/WrongNotePage.jsx
  vite.config.js
Labels: feature

#7 [FEAT] login register question
  .dockerignore
  package-lock.json
  src/App.css
  src/App.jsx
  src/components/login/LoginForm.jsx
  src/components/login/RegisterForm.jsx
  src/components/question/DifficultySelector.jsx
  src/components/question/LevelSelector.jsx
  src/components/question/QuestionDisplay.jsx
  src/pages/login/LoginRegisterPage.css
  src/pages/login/LoginRegisterPage.jsx
  src/pages/question/JLPTQuestionPage.css
  src/pages/question/JLPTQuestionPage.jsx
Labels: feature

#14 [REFACTOR] 코드 수정 및 구조 정리
  src/App.jsx
  src/components/AppLayout.css
  src/components/AppLayout.jsx
  src/components/Dashboard.jsx
  src/components/bar/Sidebar.jsx
  src/components/bar/TopBar.css
  src/components/bar/TopBar.jsx
  src/components/home/ProfileCard.css
  src/components/home/ProfileCard.jsx
  src/components/home/ProgressCard.css
  src/components/home/ProgressCard.jsx
  src/components/wrongnote/ExamInfoCard.css
  src/components/wrongnote/ExamInfoCard.jsx
  src/index.css
  src/pages/home/MyPage.css
  src/pages/home/MyPage.jsx
  src/pages/wrongnote/WrongNotePage.css
  src/pages/wrongnote/WrongNotePage.jsx
Labels: refactor

#19 [FEAT] create question 문제생성페이지
  package-lock.json
  src/App.jsx
  src/components/question/DifficultySelector.jsx
  src/components/question/LevelSelector.jsx
  src/components/question/QuestionDisplay.css
  src/components/question/QuestionDisplay.jsx
  src/components/question/TypeSelector.jsx
  src/pages/question/JLPTQuestionPage.css
  src/pages/question/JLPTQuestionPage.jsx
Labels: feature

#27 Refactor/23 refact question 문제생성페이지 리팩토링
  src/App.jsx
  src/pages/problem/GenerateProblemPage.css
  src/pages/problem/GenerateProblemPage.jsx
  src/pages/problem/ResultPage.css
  src/pages/problem/ResultPage.jsx
  src/pages/problem/SolveProblemPage.css
  src/pages/problem/SolveProblemPage.jsx
Labels: refactor

#35 [ENHANCE] nginx 도입, 설정 추가
  Dockerfile
  nginx/nginx.conf
Labels: enhancement

#40 [REFACTOR] 회원가입, 로그인 페이지 입력값 확인 검증 개선
  src/App.jsx
  src/components/bar/TopBar.jsx
  src/components/home/ProfileCard.jsx
  src/components/login/LoginForm.jsx
  src/components/login/LoginForm.module.css
  src/components/login/RegisterForm.jsx
  src/components/login/RegisterForm.module.css
  src/pages/login/LoginPage.jsx
  src/pages/login/LoginPage.module.css
  src/pages/login/RegisterPage.jsx
  src/pages/login/RegisterPage.module.css
  src/pages/profile/ProfileEditPage.jsx
  src/pages/profile/ProfileEditPage.module.css
Labels: refactor

#43 [BUGFIX] support refact 문제 생성 후 DB 저장 리팩토링 완료
  src/pages/problem/SolveProblemPage.jsx
Labels: bug fix, refactor

#47 [FEAT] 프로필 수정 페이지 추가 및 비밀번호 관련 연동
  src/api/authApi.jsx
  src/pages/profile/ProfileEditPage.jsx
Labels: feature

#49 [BUG] duplication create db중복 문제 해결
  src/pages/problem/ResultPage.jsx
  src/pages/problem/SolveProblemPage.jsx
Labels: bug fix

#53 [REFACTOR] Sidebar 관련 작업
  package-lock.json
  package.json
  src/components/bar/Sidebar.jsx
  src/components/bar/Sidebar.module.css
  src/components/bar/TopBar.css
  src/index.css
  src/pages/wrongnote/WrongNotePage.jsx
  src/pages/wrongnote/WrongNotePage.module.css
Labels: feature, refactor

#54 [FEAT] 오답노트 다시풀기 버튼 구현
  src/App.jsx
  src/pages/problem/RetryProblemPage.jsx
  src/pages/wrongnote/WrongNotePage.jsx
Labels: feature

#56 [FEAT] 전체 오답률 연동
  src/components/home/ProgressCard.css
  src/pages/home/MyPage.css
  src/pages/home/MyPage.jsx
Labels: feature

#57 [FEAT] 51-feature-support / support 페이지 구현 완료
  src/App.jsx
  src/pages/SupportPage.jsx
  src/pages/support/SupportPage.css
  src/pages/support/SupportPage.jsx
Labels: feature

#62 [FEAT] 전체 다시 풀기 기능 구현
  src/App.jsx
  src/components/bar/Sidebar.jsx
  src/pages/wrongnote/RetryAllPage.jsx
  src/pages/wrongnote/RetryAllPage.module.css
  src/pages/wrongnote/WrongNotePage.jsx
Labels: feature

#66 [ETC] gitignore, Dockerfile, dockerignore 설정 검토
  .dockerignore
  .gitignore
  Dockerfile
  src/api/authApi.jsx
Labels: etc

#67 Feat/58 chatbot feature 챗봇페이지 임시 pr 요청
  src/App.jsx
  src/components/bar/Sidebar.module.css
  src/pages/CustomPage.jsx
  src/pages/ReviewPage.jsx
  src/pages/SettingsPage.jsx
  src/pages/custom/CustomPage.css
  src/pages/custom/CustomPage.jsx
  vite.config.js
Labels: feature

#70 [FIX] fix/69-docker-compose-available
  Dockerfile
  nginx/nginx.conf
  src/App.jsx
  src/pages/home/MyPage.jsx
  src/pages/problem/GenerateProblemPage.jsx
  src/pages/problem/SolveProblemPage.jsx
  src/pages/wrongnote/WrongNotePage.jsx
  vite.config.js
Labels: bug fix, etc, refactor

#73 [ENHANCE] 문제 생성 페이지 로딩 스피너 추가
  .github/workflows/main.yml
  src/pages/problem/GenerateProblemPage.css
  src/pages/problem/GenerateProblemPage.jsx
Labels: enhancement
